### ISSUE TITLE
Refresh missing styles fails.

### ISSUE THREAD

**Issue by lephyrius** [thoughtbot/paperclip#1030]
I get this message when I try to reprocess the missing styles.(I added some new styles)
```
undefined method `body' for nil:NilClass
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/storage/fog.rb:150:in `copy_to_local_file'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/io_adapters/attachment_adapter.rb:25:in `copy_to_tempfile'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/io_adapters/attachment_adapter.rb:19:in `cache_current_values'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/io_adapters/attachment_adapter.rb:11:in `initialize'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/io_adapters/registry.rb:29:in `new'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/io_adapters/registry.rb:29:in `for'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/attachment.rb:91:in `assign'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/attachment.rb:296:in `reprocess!'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:34:in `block (5 levels) in <top (required)>'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/helpers.rb:36:in `block in each_instance_with_attachment'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/batches.rb:21:in `block (2 levels) in find_each'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/batches.rb:21:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/batches.rb:21:in `block in find_each'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/batches.rb:72:in `find_in_batches'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/batches.rb:20:in `find_each'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/paperclip/helpers.rb:35:in `each_instance_with_attachment'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:33:in `block (4 levels) in <top (required)>'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:32:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:32:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:71:in `block (5 levels) in <top (required)>'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:66:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:66:in `block (4 levels) in <top (required)>'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:65:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.2.0/lib/tasks/paperclip.rake:65:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/app/vendor/bundle/ruby/1.9.1/bin/rake:19:in `load'
/app/vendor/bundle/ruby/1.9.1/bin/rake:19:in `<main>'
Tasks: TOP => paperclip:refresh:missing_styles
```

**Comment by maclover7** [comment]
Hi @lephyrius and @k1w1 ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Given there's no activity around this issue any more, I hope things are working well for you now. I’ll close the issue, happy to continue further discussion if we can find the problem and potential fix for it. Thanks for your input!

**Comment by JONBRWN** [comment]
@tute @maclover7 ran into this today when running `paperclip:refresh:thumbnails CLASS=MyClass`

It appears to un-scope the class and included deleted objects which caused it to not find the file on S3.

Let me know if there are any additional details I can provide.

**Comment by tute** [comment]
@JONBRWN on what version of paperclip? How can we replicate it? Thanks!

**Comment by JONBRWN** [comment]
@tute Paperclip v.4.2.1

can be replicated with an attachment where the original file is no longer on S3 and then running `paperclip:refresh:thumbnails`

**Comment by jGRUBBS** [comment]
@tute and @JONBRWN jumping in here. I believe this happens when using a gem like `paranoia` where records are "soft" deleted. The items on S3 are then deleted but the model instance is still in the DB with a `deleted_at` column set. However when `paperclip:refresh:thumbnails` is run it unscopes the query and all records are trying to be reprocessed even if they are "deleted." The crux of this issue is that the wrong error is being raised in the `fog#copy_to_local_file` method making the user believe something is wrong.
