### ISSUE TITLE
Automatic S3 retries?

### ISSUE THREAD

**Issue by swrobel** [thoughtbot/paperclip#1063]
Seeing the following occasionally in a massive (~2,000 object) rake task that I'm running. Is there some way to have AWS-SDK retry automatically once or twice? This kills my whole rake task...

```
[AWS S3 200 0.435876 0 retries] head_object(:bucket_name=>"xyz",:key=>"123")  

rake aborted!
500 Internal Server Error
/Users/swrobel/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:346:in `open_http'
/Users/swrobel/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
/Users/swrobel/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
/Users/swrobel/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
/Users/swrobel/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
/Users/swrobel/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
/Users/swrobel/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:677:in `open'
/Users/swrobel/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:29:in `open'
/Users/swrobel/.rvm/gems/ruby-1.9.3-p286@stacksocial/gems/paperclip-3.1.4/lib/paperclip/io_adapters/uri_adapter.rb:16:in `download_content'
/Users/swrobel/.rvm/gems/ruby-1.9.3-p286@stacksocial/gems/paperclip-3.1.4/lib/paperclip/io_adapters/uri_adapter.rb:7:in `initialize'
/Users/swrobel/.rvm/gems/ruby-1.9.3-p286@stacksocial/gems/paperclip-3.1.4/lib/paperclip/io_adapters/registry.rb:29:in `new'
/Users/swrobel/.rvm/gems/ruby-1.9.3-p286@stacksocial/gems/paperclip-3.1.4/lib/paperclip/io_adapters/registry.rb:29:in `for'
/Users/swrobel/.rvm/gems/ruby-1.9.3-p286@stacksocial/gems/paperclip-3.1.4/lib/paperclip/attachment.rb:91:in `assign'
/Users/swrobel/.rvm/gems/ruby-1.9.3-p286@stacksocial/gems/paperclip-3.1.4/lib/paperclip.rb:196:in `block in has_attached_file'
```

**Comment by maclover7** [comment]
Hi @swrobel ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by swrobel** [comment]
No idea, haven't used paperclip in over a year

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
