### ISSUE TITLE
In what circumstance would I get: [No handler found for ""] exception?

### ISSUE THREAD

**Issue by haejeong87** [thoughtbot/paperclip#1145]
Hello, I am using Paperclip with Mongoid on Rails 3.2.11

Before using Mongoid, I was using MongoMapper, and everything was working fine. But after switching to Mongoid, I am suddenly getting [No handler found for ""] exceptions when I try to upload an image.

Could you help me a little bit in understanding what [No handler found for ""] is about?

`No handler found for ""
... /paperclip-3.4.0/lib/paperclip/io_adapters/registry.rb:19:in 'handler_for'
... /paperclip-3.4.0/lib/paperclip/io_adapters/registry.rb:29:in 'for'
... /paperclip-3.4.0/lib/paperclip/attachment.rb:93:in 'assign'
... /paperclip-3.4.0/lib/paperclip.rb:199:in 'block in has_attached_file'`

Thank you very much!

**Comment by maclover7** [comment]
Hi @nubber ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Given there's no activity around this issue any more, I hope things are working well for you now. I’ll close the issue, happy to continue further discussion if we can find the problem and potential fix for it. Thanks for your input!
