### ISSUE TITLE
No route matches error when using url obfuscation.

### ISSUE THREAD

**Issue by jan0sch** [thoughtbot/paperclip#1222]
Hi,

I'm using paperclip and have activated url obfuscation. But if I click on a download link I  get a no route matches error:

```
Started GET "/system/0dbddb09315d38e9f5efa8dde7d91cf13780fcc7.pdf?1366357823" for 127.0.0.1 at 2013-04-19 09:50:27 +0200

ActionController::RoutingError (No route matches [GET] "/system/0dbddb09315d38e9f5efa8dde7d91cf13780fcc7.pdf"):
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in `call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.13) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /usr/local/lib/ruby/1.9/webrick/httpserver.rb:138:in `service'
  /usr/local/lib/ruby/1.9/webrick/httpserver.rb:94:in `run'
  /usr/local/lib/ruby/1.9/webrick/server.rb:191:in `block in start_thread'
```

The attachment is defined in the model as follows:

```ruby
has_attached_file :data, :path => ":rails_root/public/system/abstracts/:attachment/:id/:style/:filename",
                    :url => "/system/:hash.:extension",
                    :hash_secret => "M6bGXSKkhh6s0bInm2eJz92ZQK4ka0N0PVMcL8epxP14sZKUiHvJEY8sGtrwUJGZ"
```

Environment:
* ruby 1.9.3
* rails 3.2.13
* paperclip 3.4.1

I have checked the documentation, the source and the search engines but found no clue.

Do I have to setup custom routing for this?

**Comment by maclover7** [comment]
Hi @jan0sch ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by jan0sch** [comment]
Well 2 years is quite some time. ;-)

If I remember correctly the hint from @MartinodF helped me out.
The following code works

```
  has_attached_file :data, :path => ':rails_root/public/system/abstracts/:attachment/:id/:style/:filename',
                    :url => '/system/abstracts/:attachment/:id/:style/:filename'
```

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by tute** [comment]
Thank you all!
