### ISSUE TITLE
undefined method before_<attachment>_post_process

### ISSUE THREAD

**Issue by anujbiyani** [thoughtbot/paperclip#1340]
Recently upgraded from Paperclip 3.2.1 to 3.5.1 and I'm getting the following issue when I run `rake`:
```
rake aborted!
undefined method `before_asset_post_process' for #<Class:0x007fc73e3821d0>
/Users/abiyani/.rvm/gems/ruby-1.9.3-p194@lytro/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
/Users/abiyani/.rvm/gems/ruby-1.9.3-p194@lytro/gems/paperclip-3.5.1/lib/paperclip/validators.rb:58:in `create_validating_before_filter'
/Users/abiyani/.rvm/gems/ruby-1.9.3-p194@lytro/gems/paperclip-3.5.1/lib/paperclip/validators.rb:51:in `block in validate_before_processing'
/Users/abiyani/.rvm/gems/ruby-1.9.3-p194@lytro/gems/paperclip-3.5.1/lib/paperclip/validators.rb:49:in `each'
/Users/abiyani/.rvm/gems/ruby-1.9.3-p194@lytro/gems/paperclip-3.5.1/lib/paperclip/validators.rb:49:in `validate_before_processing'
/Users/abiyani/.rvm/gems/ruby-1.9.3-p194@lytro/gems/paperclip-3.5.1/lib/paperclip/validators/attachment_presence_validator.rb:22:in `validates_attachment_presence'
/Users/abiyani/code/lytro/app/models/picture.rb:66:in `<class:Picture>'
/Users/abiyani/code/lytro/app/models/picture.rb:1:in `<top (required)>'
[truncated]
```

Asset is the name of my attachment:
```ruby
class Picture < ActiveRecord::Base
  has_attached_file :asset, { misc: 'settings' }
end
```

This is the code at the top of the stacktrace (before `method_missing`):
```ruby
def create_validating_before_filter(attribute, validator_class, options)
  if_clause = options.delete(:if)
  unless_clause = options.delete(:unless)
  send(:"before_#{attribute}_post_process", :if => if_clause, :unless => unless_clause) do |*args|
    validator_class.new(options.dup).validate(self)
  end
end
```

If I inspect `self` inside the above method, then I get the `Picture` class. But if I inspect`self.class` inside the method, then I get `'Class'`. Not sure if that's the right behavior or not, or if it's even relevant.
```ruby
p self #=> Picture(id: integer, [misc_attributes])
p self.class #=> Class
```

Any idea what's wrong? Defining this method inside my `Picture` class doesn't help, presumably because `send(:"before_#{attribute}_post_process", :if => if_clause, :unless => unless_clause)` is trying to send the method to class `Class` instead of class `Picture`.

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by anujbiyani** [comment]
No longer working on the project that led me to create this issue and I haven't been able to reproduce it.

**Comment by scmx** [comment]
@maclover7 
Yes, the issue is still there in paperclip 4.2.1.
I'm upgrading an application right now from to paperclip 3.4.2 (rails 3.2) to paperclip 4.2.1 (rails 4)
```
lib/ruby/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `before_image_post_process' for Photo (call 'Photo.connection' to establish a
connection):Class (NoMethodError)
from paperclip-4.2.1/lib/paperclip/validators.rb:67:in `create_validating_before_filter'
from paperclip-4.2.1/lib/paperclip/validators.rb:60:in `block in validate_before_processing'
from paperclip-4.2.1/lib/paperclip/validators.rb:58:in `each'
from paperclip-4.2.1/lib/paperclip/validators.rb:58:in `validate_before_processing'
from paperclip-4.2.1/lib/paperclip/validators/attachment_content_type_validator.rb:84:in `validates_attachment_content_type'
from paperclip-4.2.1/lib/paperclip/validators.rb:48:in `block (2 levels) in validates_attachment'
from paperclip-4.2.1/lib/paperclip/validators.rb:46:in `each'
from paperclip-4.2.1/lib/paperclip/validators.rb:46:in `block in validates_attachment'
from paperclip-4.2.1/lib/paperclip/validators.rb:38:in `each'
from paperclip-4.2.1/lib/paperclip/validators.rb:38:in `validates_attachment'
from app/models/photo.rb:7:in `<class:Photo>'
from app/models/photo.rb:1:in `<top (required)>'
```

But it was easily solved like this for me
```diff
+  has_attached_file :image, :styles => { :original => "922x922>", :thumb => "220x220>" }
+
   validates_presence_of :image
   validates_attachment :image, :presence => true,
   :content_type => { :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }

-  has_attached_file :image, :styles => { :original => "922x922>", :thumb => "220x220>" }
-
```

**Comment by tute** [comment]
> You need to put your validation code after the attachment declaration.

If this is not clear from the README (https://github.com/thoughtbot/paperclip/#validations), we should add a sentence on this requirement. Door is open for the new PR! :)
