### ISSUE TITLE
Image with a '%' in filename return an ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by jeromelefeuvre** [thoughtbot/paperclip#1413]
Hi,

I testing with `paperclip-demo` my problem and it failing:
````
[2014-01-10 11:58:25] ERROR ArgumentError: invalid byte sequence in UTF-8
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/multipart/parser.rb:140:in `=~'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/multipart/parser.rb:140:in `!~'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/multipart/parser.rb:140:in `get_filename'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/multipart/parser.rb:101:in `get_current_head_and_filename_and_content_type_and_name_and_body'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/multipart/parser.rb:19:in `block in parse'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/multipart/parser.rb:17:in `loop'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/multipart/parser.rb:17:in `parse'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/multipart.rb:25:in `parse_multipart'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/request.rb:336:in `parse_multipart'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/request.rb:201:in `POST'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/methodoverride.rb:26:in `method_override'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/methodoverride.rb:14:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-3.2.13/lib/action_dispatch/middleware/static.rb:63:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/engine.rb:479:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/application.rb:223:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/rack/log_tailer.rb:17:in `call'
	/Users/jeromelefeuvre/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
	/Users/jeromelefeuvre/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/Users/jeromelefeuvre/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/Users/jeromelefeuvre/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
````

**Comment by maclover7** [comment]
Hi @jeromelefeuvre and @5minpause ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Given there's no activity around this issue any more, I hope things are working well for you now. I’ll close the issue, happy to continue further discussion if we can find the fix for it. Thanks for your input!
