### ISSUE TITLE
Closed Stream - file_adapter.rb:15:in `size'

### ISSUE THREAD

**Issue by paladini** [thoughtbot/paperclip#1415]
Sometime ago I used Paperclip like a charm in [my project](http://www.btc-stores.com/), but now I'm getting a lot of errors (I solved some of them).

I make a little crawler to take snapshots of some websites, and now when I try to update the DB running a `Rake Task`, paperclip give me an error. I already cleaned all database, deleted all old folders where paperclip normally store the images. I also have been working on this bug during one week and until the moment, I didn't found the solution. 

I'm using Elementary OS (Ubuntu 12.04 based), and when I run `which convert` I get: "/usr/bin/convert". 

**Development.rb:**
```Paperclip.options[:command_path] = "/usr/bin/"```

**Item.rb (model):**
```ruby
has_attached_file :image,
	:styles => { :small => "200x147#" }, 
	:convert_options => { :small => "-quality 75 -strip" },
	:default_url => '/images/:style/bitcoin-earth.jpg'

validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
	validates_attachment_presence :image
before_validation 'self.image = get_image(self.id, self.url_original)'

# I already tried do this with TempFile, and it give me some other errors
def get_image(filename, link)
	   file_name = Rails.root.to_s + "/tmp/template_#{filename.to_s}.png"

	   kit = IMGKit.new(link.to_s)
	   file = kit.to_file(file_name.to_s)
	   return file
end
```

The error is the following:
```ruby
rake aborted!
closed stream
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/paperclip-3.5.2/lib/paperclip/io_adapters/file_adapter.rb:15:in `size'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/paperclip-3.5.2/lib/paperclip/io_adapters/file_adapter.rb:15:in `cache_current_values'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/paperclip-3.5.2/lib/paperclip/io_adapters/file_adapter.rb:5:in `initialize'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/paperclip-3.5.2/lib/paperclip/io_adapters/registry.rb:29:in `new'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/paperclip-3.5.2/lib/paperclip/io_adapters/registry.rb:29:in `for'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/paperclip-3.5.2/lib/paperclip/attachment.rb:96:in `assign'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/paperclip-3.5.2/lib/paperclip/has_attached_file.rb:65:in `block in define_setter'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:377:in `_run__408645080__validation__callbacks'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activemodel-4.0.0/lib/active_model/validations/callbacks.rb:106:in `run_validations!'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activemodel-4.0.0/lib/active_model/validations.rb:314:in `valid?'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/validations.rb:70:in `valid?'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/validations.rb:77:in `perform_validations'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/validations.rb:51:in `save'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:32:in `save'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block (2 levels) in save'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block in save'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/gems/activerecord-4.0.0/lib/active_record/transactions.rb:269:in `save'
/home/paladini/Documents/Projetos/bittle/btc-stores/lib/tasks/data.rake:104:in `block (3 levels) in <top (required)>'
/home/paladini/Documents/Projetos/bittle/btc-stores/lib/tasks/data.rake:56:in `each'
/home/paladini/Documents/Projetos/bittle/btc-stores/lib/tasks/data.rake:56:in `block (2 levels) in <top (required)>'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/bin/ruby_executable_hooks:15:in `eval'
/home/paladini/.rvm/gems/ruby-2.0.0-p353@btc-stores/bin/ruby_executable_hooks:15:in `<main>'
```

And my gemfile (tried a lot of combinations, put and retired "cocaine" a lot of times):
```ruby 
gem "paperclip"
```

I'm working hard on [BTC-Stores](http://www.btc-stores.com) in the last weeks and I need publish the changes soon, because I'm coming back to work and I don't will have a lot of time to work in it. Please, can you help me? :(

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Given there's no activity around this issue any more, I hope things are working well for you now. I’ll close the issue, happy to continue further discussion if we can find the fix for it. Thanks for your input!
