### ISSUE TITLE
[Convert to PDF processor] IOError – closed stream

### ISSUE THREAD

**Issue by ostera** [thoughtbot/paperclip#1582]
Hi, I'm running Paperclip 4.1.1 and I have a processor to convert files to pdf using libreoffice headless, but it's giving me this error:
```
IOError - closed stream:
  /Users/leostera/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/delegate.rb:295:in `block in delegating_block'
  paperclip (4.1.1) lib/paperclip/io_adapters/abstract_adapter.rb:8:in `rewind'
  paperclip (4.1.1) lib/paperclip/storage/filesystem.rb:52:in `block in flush_writes'
  paperclip (4.1.1) lib/paperclip/storage/filesystem.rb:37:in `flush_writes'
  paperclip (4.1.1) lib/paperclip/attachment.rb:239:in `save'
  paperclip (4.1.1) lib/paperclip/has_attached_file.rb:88:in `block in add_active_record_callbacks'
  activesupport (4.0.4) lib/active_support/callbacks.rb:430:in `_run__1298101045684281736__save__callbacks'
```

The processor is pretty small itself:
```rb
    1 module Paperclip
    2   class Convert < Processor
    3
    4     def make #file, options, attachment
    5       soffice = %x{/usr/bin/env which soffice}
    6       if soffice.empty?
    7         soffice = "/Applications/LibreOffice.app/Contents/MacOS/soffice"
    8       end
    9
   10       cmd = %Q(#{soffice}
   11                 --headless
   12                 --convert-to pdf
   13                 --outdir #{File.dirname(file.path)}
   14                 #{file.path}).gsub("\n","")
   15
   16       `#{cmd}`
   17
   18       basename = File.basename(file.path)
   19       file_name = [basename, "pdf"].join(".")
   20       new_path = "#{File.dirname(file.path)}/#{file_name}"
   21       new_file = File.open(new_path)
   22
   23       attachment.instance.send("#{attachment.name}=", new_file)
   24
   25       new_file
   26     end
   27
   28   end
   29 end
```

And I'm not sure if this has something to do with returning a new File, or if I should be wrapping my new file in a Paperclip::UploadedFileAdaptor.

**Comment by maclover7** [comment]
Hi @leostera ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Given there's no activity around this issue anymore, I hope things are working well now for you. I’ll close the issue, happy to continue further discussion if we can find the problem and potential fix for it. Thanks for your input!
