### ISSUE TITLE
Can't download attachment from S3: OpenURI::HTTPError: 403 Forbidden

### ISSUE THREAD

**Issue by rodrigoalvesvieira** [thoughtbot/paperclip#1600]
Hello everyone,

I have a Rails 4.1.1 app with Paperclip uploading files to Amazon S3 and I have a method somewhere in my `lib/` folder where I get the file url from S3 to do some post-processing. My code is like this:

```ruby
def process_file(file_url)
  file =  open(file_url)
  ...
end
```

However, every time this method gets called, I get a `OpenURI::HTTPError: 403 Forbidden`  error.

Why is that happening? I just copied and pasted the file url into my browser and it is downloaded just fine.

I've searched the web and this seems to be rather a common problem, but none of the suggested fixes worked for me. Hope I can get some help 'cause I have no idea on how to solve this anymore.

Thanks,

-- Rodrigo

**Comment by maclover7** [comment]
Hi @rodrigoalvesvieira ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by rodrigoalvesvieira** [comment]
Hello @maclover7 didn't even remember this issue. As far as my memory goes, I don't recall exactly how I fixed the bug, but it was something related to OpenSSL or some other library like that

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by uriklar** [comment]
I'm getting this error with Rails 3. 
The line is: 
```
image.photo = URI.parse(URI.escape(image.direct_upload_url)) 
```

I'm assigning to my model's attached_file 

The stack trace is: 
```
2015-06-11T07:30:12Z 3 TID-ot6iejei8 WARN: 403 Forbidden
2015-06-11T07:30:12.087469+00:00 app[worker.1]: 2015-06-11T07:30:12Z 3 TID-ot6iejei8 WARN: /app/vendor/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:353:in `open_http'
2015-06-11T07:30:12.087472+00:00 app[worker.1]: /app/vendor/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:723:in `buffer_open'
2015-06-11T07:30:12.087473+00:00 app[worker.1]: /app/vendor/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
2015-06-11T07:30:12.087475+00:00 app[worker.1]: /app/vendor/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
2015-06-11T07:30:12.087477+00:00 app[worker.1]: /app/vendor/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
2015-06-11T07:30:12.087479+00:00 app[worker.1]: /app/vendor/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
2015-06-11T07:30:12.087480+00:00 app[worker.1]: /app/vendor/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:703:in `open'
2015-06-11T07:30:12.087482+00:00 app[worker.1]: /app/vendor/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:30:in `open'
2015-06-11T07:30:12.087484+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.1.0/gems/paperclip-3.5.2/lib/paperclip/io_adapters/uri_adapter.rb:17:in `download_content'
2015-06-11T07:30:12.087485+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.1.0/gems/paperclip-3.5.2/lib/paperclip/io_adapters/uri_adapter.rb:7:in `initialize'
2015-06-11T07:30:12.087487+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.1.0/gems/paperclip-3.5.2/lib/paperclip/io_adapters/registry.rb:29:in `new'
2015-06-11T07:30:12.087489+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.1.0/gems/paperclip-3.5.2/lib/paperclip/io_adapters/registry.rb:29:in `for'
2015-06-11T07:30:12.087490+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.1.0/gems/paperclip-3.5.2/lib/paperclip/attachment.rb:96:in `assign'
2015-06-11T07:30:12.087492+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.1.0/gems/paperclip-3.5.2/lib/paperclip/has_attached_file.rb:65:in `block in define_setter'
2015-06-11T07:30:12.087494+00:00 app[worker.1]: /app/app/models/photo.rb:61:in `transfer_and_cleanup'
```

I'm trying to get the image from an S3 bucket and run some post processing on it. Any ideas?
