### ISSUE TITLE
Geometry.from_file with ImageMagick 6.8.9 "identify: must specify image size"

### ISSUE THREAD

**Issue by nathany** [thoughtbot/paperclip#1693]
I'm seeing the all too common `Paperclip::Errors::NotIdentifiedByImageMagickError`. It's coming from this bit of code:

```ruby
Paperclip::Geometry.from_file(paperclip_attachment.url(style))
```

The logs show the following command (the file is uploaded directly to S3). 

```
Command :: identify -format '%wx%h,%[exif:orientation]' 'https://jobber-development-nathany.s3.amazonaws.com/temp_logo_uploader_logos/10413/original/jobber-photo.jpg%3F1415659726[0]' 2>/dev/null
```

Running this on the command line gives the error **identify: must specify image size**:

```console
identify -format '%wx%h,%[exif:orientation]' 'https://jobber-development-nathany.s3.amazonaws.com/temp_logo_uploader_logos/10413/original/jobber-photo.jpg%3F1415659726[0]'
identify: must specify image size `/var/tmp/magick-40206EKB8avnohD8X' @ error/mvg.c/ReadMVGImage/185.
```

This is occurring with ImageMagick 6.8.9

```
identify --version
Version: ImageMagick 6.8.9-8 Q16 x86_64 2014-10-23 http://www.imagemagick.org
Version: ImageMagick 6.8.9-7 Q16 x86_64 2014-11-03 http://www.imagemagick.org
```

The code works perfectly for a developer with a prior version of ImageMagick (and it was working fine for me some time ago, before upgrading):

```
ImageMagick 6.8.8-9 Q16 x86_64 2014-03-23
```

The logs also contain:

```
Paperclip::Errors::NotIdentifiedByImageMagickError - Paperclip::Errors::NotIdentifiedByImageMagickError:
   () Users/nathany/.rvm/gems/ruby-2.1.4/bundler/gems/paperclip-804b4edc1d8d/lib/paperclip/geometry_detector_factory.rb:10:in `make'
   () Users/nathany/.rvm/gems/ruby-2.1.4/bundler/gems/paperclip-804b4edc1d8d/lib/paperclip/geometry.rb:26:in `from_file'
  lib/model_modules/cropper.rb:40:in `paperclip_image_geometry'
```

We are all running on OS X with ImageMagick installed via Homebrew. Unfortunately Homebrew doesn't provide a good way to install past versions, so I haven't 100% confirmed that this only occurs in the newer version. Has anyone else ran into this issue?

P.S. We are running Paperclip 4.1.0 in production (see https://github.com/thoughtbot/paperclip/issues/1634), but I have also tested with 4.2.0 and against master. Same issue every time.

**Comment by nathany** [comment]
Thanks @d0minikk
