### ISSUE TITLE
Converting image from another non-original one breaks reprocessing

### ISSUE THREAD

**Issue by paulslaby** [thoughtbot/paperclip#1695]
I have these processors: 

```
module Paperclip
  class Cropper < Thumbnail
    ... (omitted)
  end

  class RecursiveThumbnail < Thumbnail
    def initialize file, options = {}, attachment = nil
      super Paperclip.io_adapters.for(attachment.styles[:small]), options, attachment
    end
  end
end
```

Attachment is defined like this: 
```
has_attached_file :avatar,
    :styles => ActiveSupport::OrderedHash.new.tap do |styles|
      styles[:small] = {geometry: '200x200!', processors: [:cropper]}
      styles[:icon] = {geometry: '50x50', processors: [:recursive_thumbnail]}
    end
```

So I crop image to small one. Now I want to make an icon from the small one. I works ok, when I process it at once. But when I try `model.reprocess! :icon`, it fails with this error: 
```
NoMethodError: undefined method `path' for nil:NilClass
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:172:in `staged_path'
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/io_adapters/attachment_adapter.rb:25:in `copy_to_tempfile'
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/io_adapters/attachment_adapter.rb:19:in `cache_current_values'
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/io_adapters/attachment_adapter.rb:11:in `initialize'
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/io_adapters/registry.rb:29:in `new'
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/io_adapters/registry.rb:29:in `for'
	from /Users/paulie/Work/hlidacky/hlidacky.cz/config/initializers/cropper.rb:23:in `initialize'
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/processor.rb:33:in `new'
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/processor.rb:33:in `make'
	from /Users/paulie/.rvm/gems/ruby-1.9.3-p547/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:523:in `block in post_process_style'
(more omitted)
```

I sniffed out that `@queued_for_write` does not contain small because it was not processed. 
When paperclip doesn't use staged_path, but path, it works ok. 

What is the right way to get it working?

**Comment by dmitry** [comment]
@paulslaby what paperclip version do you have?

**Comment by paulslaby** [comment]
I am not working on that project anymore. I am forwarding link to this issue through other comm channel to person, who might be still interested.

**Comment by petrsigut** [comment]
@dmitry we switched to carrierwave, can't reproduce it now, sorry.

**Comment by dmitry** [comment]
I think an issue was before 4.2.0. For me it looks like issue can be closed now.

**Comment by tute** [comment]
Thank you all.
