### ISSUE TITLE
Undefined method `attachment'

### ISSUE THREAD

**Issue by webhat** [thoughtbot/paperclip#1721]
I started an empty project with the `Gemfile`:

```
source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'rspec-rails'

gem 'paperclip'
```

And got this error while running `rake db:migrate`:

```
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `attachment' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x007fcf5c3d30f0>/Users/webhat/Development/paperclip_montage/spec/rails-app/db/migrate/20141212000615_create_avatars.rb:4:in `block in change'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:198:in `create_table'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:649:in `block in method_missing'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:621:in `block in say_with_time'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:621:in `say_with_time'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:641:in `method_missing'
/Users/webhat/Development/paperclip_montage/spec/rails-app/db/migrate/20141212000615_create_avatars.rb:3:in `change'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:595:in `exec_migration'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:578:in `block in migrate'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:577:in `migrate'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:752:in `migrate'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:991:in `block in execute_migration_in_transaction'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:1037:in `block in ddl_transaction'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:1037:in `ddl_transaction'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:990:in `execute_migration_in_transaction'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:952:in `block in migrate'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:948:in `each'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:948:in `migrate'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:807:in `up'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/migration.rb:785:in `migrate'
/Users/webhat/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Downgrading to 4.1.1 worked fine.

**Comment by afrahkariyadan** [comment]
its work for me  thanks

**Comment by tute** [comment]
It doesn't seem to be a bug in paperclip, or we can't replicate it. Can you provide a test app or branch in GitHub for us to study this issue @webhat? Thanks!

**Comment by tute** [comment]
@webhat this works for me, and should be working starting with paperclip v3.1 IIRC. If you can provide reproducing steps, we'll reopen the issue.

Thanks for your report.

**Comment by tute** [comment]
```
master % cat db/migrate/20141212000615_create_avatars.rb
class CreateAvatars < ActiveRecord::Migration
  def change
    create_table :avatars do |t|
      t.attachment :avatar

      t.timestamps
    end
  end
end

master % rake db:migrate
Array values in the parameter are deprecated. Please use a String or nil.
An Array was passed in from ./bin/rake:3:in `load'
== 20141212000615 CreateAvatars: migrating ====================================
-- create_table(:avatars)
   -> 0.0444s
== 20141212000615 CreateAvatars: migrated (0.0446s) ===========================
```
