### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by renspr** [thoughtbot/paperclip#1759]
Hi,

I have a migration that moves a user profile picture (originally uploaded by carrierwave) into a new user model. When running the migration I'll get a "Too many open files" error after ~2000 records.

The user looks like this

```ruby
class User < ActiveRecord::Base
  # ...

  # Attachments
  has_attached_file :photo,
    styles: { original: "300x300>", thumb: "100x100>" },
    convert_options: { all: '-auto-orient' }
  validates_attachment :photo,
    presence: true,
    content_type: { content_type: ["image/jpeg", "image/png"] },
    size: { in: 0..1.megabytes }

  # ...
end
```

Migration

```ruby
# ...
def up
    User.transaction do
      add_attachment :users, :photo

      # ...

      Profile.find_each do |profile|
        old_photo_path = "#{Rails.root}/public/uploads/profile/photo/#{profile.id}/cropped_#{profile.photo}"
        old_photo_file = File.open(old_photo_path)

        user = User.find(profile.user_id)
        user.photo = old_photo_file
        old_photo_file.close
        user.save!(validate: false)
      end
    end
  end
```

The stacktrace

````
Too many open files - file -b --mime '/var/folders/04/1w0ww06n349268r2hzztmfhm0000gn/T/5c8f0509e04f55507a03c86beb22cfbe20150131-73323-43bmjw20150131-73323-6bqono'/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:32:in `spawn'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:32:in `spawn'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:21:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line.rb:136:in `execute'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line.rb:75:in `run'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/helpers.rb:31:in `run'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/file_command_content_type_detector.rb:18:in `type_from_file_command'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/file_command_content_type_detector.rb:10:in `detect'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/content_type_detector.rb:61:in `type_from_file_command'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/content_type_detector.rb:36:in `detect'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/io_adapters/file_adapter.rb:14:in `cache_current_values'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/io_adapters/file_adapter.rb:5:in `initialize'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/io_adapters/registry.rb:29:in `new'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/io_adapters/registry.rb:29:in `for'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:528:in `post_process_style'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:512:in `block in post_process_styles'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:511:in `each'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:511:in `post_process_styles'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:503:in `block (2 levels) in post_process'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_photo_post_process_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/callbacks.rb:36:in `run_paperclip_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:501:in `block in post_process'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_post_process_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/callbacks.rb:36:in `run_paperclip_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:500:in `post_process'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:456:in `post_process_file'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:108:in `assign'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
/Users/renspr/Code/Projects/tickettoaster/crewtool/db/migrate/20150129150327_merge_user_profile_into_user.rb:20:in `block (2 levels) in up'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
/Users/renspr/Code/Projects/tickettoaster/crewtool/db/migrate/20150129150327_merge_user_profile_into_user.rb:15:in `block in up'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/renspr/Code/Projects/tickettoaster/crewtool/db/migrate/20150129150327_merge_user_profile_into_user.rb:7:in `up'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/renspr/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/renspr/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Errno::EMFILE: Too many open files - file -b --mime '/var/folders/04/1w0ww06n349268r2hzztmfhm0000gn/T/5c8f0509e04f55507a03c86beb22cfbe20150131-73323-43bmjw20150131-73323-6bqono'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:32:in `spawn'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:32:in `spawn'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:21:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line.rb:136:in `execute'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line.rb:75:in `run'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/helpers.rb:31:in `run'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/file_command_content_type_detector.rb:18:in `type_from_file_command'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/file_command_content_type_detector.rb:10:in `detect'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/content_type_detector.rb:61:in `type_from_file_command'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/content_type_detector.rb:36:in `detect'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/io_adapters/file_adapter.rb:14:in `cache_current_values'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/io_adapters/file_adapter.rb:5:in `initialize'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/io_adapters/registry.rb:29:in `new'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/io_adapters/registry.rb:29:in `for'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:528:in `post_process_style'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:512:in `block in post_process_styles'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:511:in `each'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:511:in `post_process_styles'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:503:in `block (2 levels) in post_process'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_photo_post_process_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/callbacks.rb:36:in `run_paperclip_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:501:in `block in post_process'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_post_process_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/callbacks.rb:36:in `run_paperclip_callbacks'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:500:in `post_process'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:456:in `post_process_file'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:108:in `assign'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/paperclip-4.2.1/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
/Users/renspr/Code/Projects/tickettoaster/crewtool/db/migrate/20150129150327_merge_user_profile_into_user.rb:20:in `block (2 levels) in up'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
/Users/renspr/Code/Projects/tickettoaster/crewtool/db/migrate/20150129150327_merge_user_profile_into_user.rb:15:in `block in up'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/renspr/Code/Projects/tickettoaster/crewtool/db/migrate/20150129150327_merge_user_profile_into_user.rb:7:in `up'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/renspr/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/renspr/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/renspr/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
``` 

I'm unsure if this is a bug or if I'm doing something wrong. Closing the file right after assigning it to the attachment does't solve this issue though.

Regards, René

**Comment by adrianotadao** [comment]
@renspr This is a file system alert. Check this [post](http://askubuntu.com/questions/181215/too-many-open-files-how-to-find-the-culprit) and try to raise the `unlimit`

**Comment by renspr** [comment]
After raising `ulimit` for `open files` the process finished successfully.

**Comment by glaucocustodio** [comment]
Same problem here, increasing `ulimit` works, but would be great to find the real cause..

**Comment by tute** [comment]
There is more discussion in: https://github.com/thoughtbot/paperclip/issues/1326

**Comment by barbolo** [comment]
Raising `ulimit` is not the way to go, it will mask the real problem.

**Comment by carloragugini** [comment]
Is there any kind of memory leak or file handlers that are not closed/released? This bug still happens with the latest stable version. And as @barbolo said, raising the `ulimit` is just the simplest way to mask the real problem.

**Comment by marzapower** [comment]
Is there any memory leak or any problem with temporary file handlers that are not closed/released after use? This bug still happens in the latest stable version (6.1.0) and does not appear to have being solved. As @barbolo stated before, changing the `ulimit` is just a simple way to mask the real problem...

**Comment by erikt9** [comment]
Just to document one possible solution and leave it somewhere for people to find 😝.  I found that using `fog-google` with paperclip would open a bunch of sockets when working with an attachment, but strangely enough `fog-aws` didn't.  Turns out the difference that mattered between the gems is the `persistent` setting is `false` by default in most aws cases, but `true` in google.  Configuring paperclip like so fixed the issue in my case:

```
fog_credentials: {
        provider: 'Google',
        google_storage_access_key_id: ...,
        google_storage_secret_access_key: ...,
        persistent: false # consistent with aws default, stops connection leaks in batches
      }
```
