### ISSUE TITLE
validates_attachment_presence :attachment on a zip file causes crash under Rails 4.1

### ISSUE THREAD

**Issue by jasonfb** [thoughtbot/paperclip#1824]
```
module Spree
  class ZipAttachment < ActiveRecord::Base
    validates_attachment_presence :attachment
 ...
  end
end
```

My app can't boot after upgrading to Rails 4.1 + paperclip (4.2.1). It crashes with this stacktrace:

2015-03-27T18:18:44.903828+00:00 app[web.1]: ** /app/app/controllers/spree/admin/store_credit_controller_decorator.rb disabled during upgrade
2015-03-27T18:18:45.138797+00:00 app[web.1]: ** /app/app/models/store_credit_decorator.rb disabled during upgrade
2015-03-27T18:18:48.482311+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `_attachment_post_process_callbacks' for #<Class:0x007ff868251080> (NoMethodError)
2015-03-27T18:18:48.482320+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:737:in `get_callbacks'
2015-03-27T18:18:48.482322+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:602:in `set_callback'
2015-03-27T18:18:48.482323+00:00 app[web.1]: 	from (eval):2:in `before_attachment_post_process'
2015-03-27T18:18:48.482325+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/validators.rb:67:in `create_validating_before_filter'
2015-03-27T18:18:48.482326+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/validators.rb:60:in `block in validate_before_processing'
2015-03-27T18:18:48.482328+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/validators.rb:58:in `each'
2015-03-27T18:18:48.482337+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/validators.rb:58:in `validate_before_processing'
2015-03-27T18:18:48.482339+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/validators/attachment_presence_validator.rb:26:in `validates_attachment_presence'
2015-03-27T18:18:48.482340+00:00 app[web.1]: 	from /app/app/models/spree/zip_attachment.rb:8:in `<class:ZipAttachment>'
2015-03-27T18:18:48.482342+00:00 app[web.1]: 	from /app/app/models/spree/zip_attachment.rb:4:in `<module:Spree>'
2015-03-27T18:18:48.482343+00:00 app[web.1]: 	from /app/app/models/spree/zip_attachment.rb:3:in `<top (required)>'
2015-03-27T18:18:48.482347+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2015-03-27T18:18:48.482348+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2015-03-27T18:18:48.482349+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
2015-03-27T18:18:48.482350+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
2015-03-27T18:18:48.482352+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
2015-03-27T18:18:48.482353+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:348:in `require_or_load'
2015-03-27T18:18:48.482354+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:307:in `depend_on'
2015-03-27T18:18:48.482355+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:225:in `require_dependency'
2015-03-27T18:18:48.482356+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
2015-03-27T18:18:48.482359+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:467:in `each'
2015-03-27T18:18:48.482360+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:467:in `block in eager_load!'
2015-03-27T18:18:48.482362+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:465:in `each'
2015-03-27T18:18:48.482363+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:465:in `eager_load!'
2015-03-27T18:18:48.482366+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:346:in `eager_load!'
2015-03-27T18:18:48.482367+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/finisher.rb:58:in `each'
2015-03-27T18:18:48.482370+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
2015-03-27T18:18:48.482371+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
2015-03-27T18:18:48.482374+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
2015-03-27T18:18:48.482377+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
2015-03-27T18:18:48.482380+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
2015-03-27T18:18:48.482383+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
2015-03-27T18:18:48.482386+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
2015-03-27T18:18:48.482388+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
2015-03-27T18:18:48.482391+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
2015-03-27T18:18:48.482394+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
2015-03-27T18:18:48.482397+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
2015-03-27T18:18:48.482400+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
2015-03-27T18:18:48.482418+00:00 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
2015-03-27T18:18:48.482443+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
2015-03-27T18:18:48.482445+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
2015-03-27T18:18:48.482448+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
2015-03-27T18:18:48.482450+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
2015-03-27T18:18:48.482453+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<top (required)>'
2015-03-27T18:18:48.482454+00:00 app[web.1]: 	from config.ru:4:in `require'
2015-03-27T18:18:48.482457+00:00 app[web.1]: 	from config.ru:4:in `block in <main>'
2015-03-27T18:18:48.482460+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
2015-03-27T18:18:48.482462+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
2015-03-27T18:18:48.482465+00:00 app[web.1]: 	from config.ru:1:in `new'
2015-03-27T18:18:48.482468+00:00 app[web.1]: 	from config.ru:1:in `<main>'
2015-03-27T18:18:48.482471+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `eval'
2015-03-27T18:18:48.482474+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `block in builder'
2015-03-27T18:18:48.482476+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `call'
2015-03-27T18:18:48.482479+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `build_app!'
2015-03-27T18:18:48.482483+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:137:in `start'
2015-03-27T18:18:48.482500+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
2015-03-27T18:18:48.482501+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
2015-03-27T18:18:48.482505+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
2015-03-27T18:18:49.380467+00:00 heroku[web.1]: Process exited with status 1
2015-03-27T18:18:49.397871+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by mvz** [comment]
@jasonfb I just solved the same issue by adding a validation on content type:

```ruby
  validates_attachment :attachment,
    presence: true,
    content_type: { content_type: %w(image/jpeg image/jpg imag/png image/gif) }
```

**Comment by maclover7** [comment]
All clear then? @mike-burns @jferris @jyurek please close issue, problem appears resolved

**Comment by tute** [comment]
ping @jasonfb. Is this still an issue for you?

**Comment by jasonfb** [comment]
nope, closing
