### ISSUE TITLE
Permission denied @ sys_fail2

### ISSUE THREAD

**Issue by nicohvi** [thoughtbot/paperclip#1825]
I've run into a weird issue.

```ruby
context 'Paperclip' do
    let(:post) { build :post }
    let(:invalid_image) { File.new("#{Rails.root}/spec/files/invalid.mp4") }
    let(:valid_image) { File.new("#{Rails.root}/spec/files/valid_image.png") }
    let(:valid_path) { "#{Rails.root}/spec/public/valid_image.png" }

    it 'doesn\'t upload an invalid image' do
      expect{ post.update_attributes!(image: invalid_image) }.to raise_error
      expect(post.errors.messages[:image]).to_not be_empty
    end

    it 'uploads a valid image' do
      expect{ post.update_attributes!(image: valid_image) }.to_not raise_error
      expect(post.image.path).to eq(valid_path)
      expect(post.image.url(:thumb)).to_not be_nil
      expect(post.image.url(:medium)).to_not be_nil
      expect(post.image.url(:large)).to_not be_nil
    end

    # remove paperclip generated files.
    after :all do
      FileUtils.rm_rf("#{Rails.root}/spec/public")
    end
  end
```

This spec runs without problems. However, when I try to seed some records using `db/seeds.rb` I run into some problems.

```ruby
# seeds.rb
50.times do |n|
  image = File.new("#{Rails.root}/spec/files/valid_image.png")

  post_params = {
    title: "Hunting dat whale for the #{n}th time",
    image: image,
    author: user
  }

  Post.create(post_params)
end
```

When I run `rake db:seed` I get the following error:

```
rake aborted!
Errno::EINVAL: Invalid argument @ rb_sysopen - D:/Code/project/public/paperclip/va
lid_image.png/
D:/Code/nplol/db/seeds.rb:15:in `block in <top (required)>'
D:/Code/nplol/db/seeds.rb:6:in `times'
D:/Code/nplol/db/seeds.rb:6:in `<top (required)>'
Errno::EACCES: Permission denied @ sys_fail2 - (C:/Users/CANHV/AppData/Local/Tem
p/df77626d5a5db477bda9a9ce48f9129320150330-17172-19kcexf.png, D:/Code/project/publ
ic/paperclip/valid_image.png/)
D:/Code/nplol/db/seeds.rb:15:in `block in <top (required)>'
D:/Code/nplol/db/seeds.rb:6:in `times'
D:/Code/nplol/db/seeds.rb:6:in `<top (required)>'
Tasks: TOP => db:seed
```

Yes, I'm on Windows (7) - sorry about that.

**edit**: Everything works perfectly on OS X.

**Comment by daniel-rikowski** [comment]
I had a similar problem, not the same location. Try disabling your antivirus. 

If that fixes the problem, you can use a retrying mechanism, something like this: (adapted from my code)

```ruby
begin
  Post.create(post_params)
rescue StandardError => ex
  if File.split($PROGRAM_NAME).last == 'rake'
    # On Windows systems sometimes the files are locked exclusively (Antivirus?)
    puts ex.message
    puts 'Retrying...'
    Kernel.sleep(1)
    retry
  else
    raise
  end
end
```

You might want to add a counter and/or a check for a specific exception, otherwise a validation error would result in an endless loop.

**Comment by jyurek** [comment]
From a quick googling, all I can find is that it's a permission error (but we knew that), and appears to come from renaming. So perhaps you don't have the permissions to your temp directory that you thought you did?

**Comment by tute** [comment]
Since it's been more than a year, I hope things are working well now for you.
Closing this issue now, and I'm happy to continue further discussion if you need. Thanks for reporting.
