### ISSUE TITLE
Could not run the `identify` command. Please install ImageMagick.

### ISSUE THREAD

**Issue by heaven** [thoughtbot/paperclip#1847]
I do run the next command (need to copy images from one model to another in random order):

```ruby
Profile.find_in_batches(:batch_size => 200) { |batch| 
  batch.each_slice(10).map { |slice| 
    Thread.new { 
      ActiveRecord::Base.connection_pool.with_connection { 
        slice.each { |profile| 
          next if profile.pictures.exists?
          
          asset = AssetImage.where(:assetable_type => "Award::Nominee").where.not(:data_file_name => nil).order("RAND()").first; 
          profile.pictures.create(:data => asset.data) 
        } 
      } 
    } 
  }.map(&:join)
  
  GC.start 
}
```

It does work for some time and then fails with the next error:
```
2.1.0 :002 > /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/geometry_detector_factory.rb:45:in `raise_because_imagemagick_missing': Could not run the `identify` command. Please install ImageMagick. (Paperclip::Errors::CommandNotFoundError)
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/geometry_detector_factory.rb:30:in `rescue in geometry_string'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/geometry_detector_factory.rb:16:in `geometry_string'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/geometry_detector_factory.rb:9:in `make'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.1/lib/paperclip/geometry.rb:26:in `from_file'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/ckeditor-4.1.1/lib/ckeditor/backend/paperclip.rb:22:in `geometry'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/ckeditor-4.1.1/lib/ckeditor/backend/paperclip.rb:40:in `read_dimensions'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:424:in `block in make_lambda'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:160:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:160:in `block in halting'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `run_callbacks'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:306:in `_create_record'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/timestamp.rb:57:in `_create_record'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/persistence.rb:483:in `create_or_update'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:302:in `block in create_or_update'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:113:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:113:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:166:in `block in halting'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:166:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:166:in `block in halting'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `call'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `run_callbacks'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:302:in `create_or_update'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/persistence.rb:103:in `save'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/validations.rb:51:in `save'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/attribute_methods/dirty.rb:21:in `save'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/transactions.rb:208:in `transaction'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/transactions.rb:268:in `block in save'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/transactions.rb:267:in `save'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/associations/has_many_association.rb:40:in `insert_record'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:44:in `block (2 levels) in create_record'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:42:in `block in create_record'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/transactions.rb:208:in `transaction'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/associations/collection_association.rb:167:in `transaction'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:41:in `create_record'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:26:in `create'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:60:in `create'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/commands/runner.rb:62:in `block (5 levels) in <top (required)>'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/commands/runner.rb:62:in `each'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/commands/runner.rb:62:in `block (4 levels) in <top (required)>'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/commands/runner.rb:62:in `block (3 levels) in <top (required)>'
	from /var/www/crm.wegohealth.com/releases/20150506123128/lib/core_ext/thread.rb:16:in `call'
	from /var/www/crm.wegohealth.com/releases/20150506123128/lib/core_ext/thread.rb:16:in `block in initialize'
```

And `which -a identify` shows `/usr/bin/identify`.

**Comment by heaven** [comment]
Just happened again and before the backtrace I saw: `sh: 1: file: not found`. So it seems the command fails because of another reason, not because the missing identify.

**Comment by jyurek** [comment]
Yeah, it seems to be unable to find the `file` command, which is odd as `file` is a standard utility on unix-like systems. Make sure that's available with `which file` and then make sure its directory is either in your `$PATH` or put it in Paperclip's PATH with `Paperclip.options[:command_path] = '<path>'`.

**Comment by heaven** [comment]
Hi, the problem is in that `It does work for some time and then fails...`. So even if something is wrong with the path – it gets broken after paperclip run, because it does work for some time. The file command present in the $PATH, just verified that. I was wondering if Paperclip.run is thread safe/could thread safety have impact on this at all.

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention
from more people than in this issue tracker.

Sorry we don't have the time now to help you with this question, and thanks!
