### ISSUE TITLE
Interpolation called on a different, unrelated model?

### ISSUE THREAD

**Issue by giuseb** [thoughtbot/paperclip#2007]
I have 2 paperclipped models with custom interpolations:

```ruby
class Figure < ActiveRecord::Base
  [...]
  belongs_to :org
  has_attached_file :image,
                     styles: { original: "1000x1000>", medium: "300x300>", thumb: "100x100>" },
                     path: ":rails_root/private/:class/:attachment/:id_partition/:style/:filename",
                     url:  "/orgs/:org_id/:class/:id/:style"

  Paperclip.interpolates :org_id  do |attachment, style|
    attachment.instance.org.id
  end
  [...]
end

class OmrSheet < ActiveRecord::Base
  [...]
  belongs_to :exam

  has_attached_file :sheet,
                     path: ":rails_root/private/:class/:attachment/:id_partition/:style/:filename",
                     url:  "/orgs/:org_id/exams/:exam_id/:class/:id/thing"

  Paperclip.interpolates :org_id  do |attachment, style|
    attachment.instance.exam.org.id
  end

  Paperclip.interpolates :exam_id  do |attachment, style|
    attachment.instance.exam.id
  end
  [...]
end
```

The problem I am experiencing appears to occur only in production (puma, and either MRI or RBX).
At the console:

```
irb(main):001:0> f = Figure.first
irb(main):002:0> f.image.url
NoMethodError: undefined method `exam' for #<Figure:0xbc5c41c8>
	from /home/rails/myapp/shared/bundle/ruby/2.2.0/gems/activemodel-4.1.12/lib/active_model/attribute_methods.rb:435:in `method_missing'
	from /home/rails/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.12/lib/active_record/attribute_methods.rb:213:in `method_missing'
	from /home/rails/myapp/releases/20150921081850/app/models/omr_sheet.rb:17:in `block in <class:OmrSheet>'
	from /home/rails/myapp/shared/bundle/ruby/2.2.0/gems/paperclip-4.3.1/lib/paperclip/interpolations.rb:34:in `block (2 levels) in interpolate'
    [...]
```
Please note the reference to `omr_sheet.rb` in the trace (in reality, line 17 is where the `:org_id` interpolation is defined) while trying to obtain the URL of a Figure. How can this happen?

I realize the complexity of my setup, and I hesitated before submitting this as an issue, please do let me know if I should provide more details and/or redirect my question elsewhere.

Thanks,
Giuseppe

**Comment by jyurek** [comment]
Unfortunately, interpolations are not local to the class. Since you have `:org_id` on both, one will take precedence. I recommend changing your interpolation names to `:figure_org_id` and `:omr_sheet_org_id`.

**Comment by giuseb** [comment]
Thanks!
Given their non-locality, wouldn't it make sense to place all interpolations in a separate file, like an initializer?

**Comment by dgynn** [comment]
@giuseb Yes. An initializer is a great location to add your custom interpolations.
