### ISSUE TITLE
Generate controller and get `method_missing': undefined method `has_attached_file'

### ISSUE THREAD

**Issue by MightyBoosh92** [thoughtbot/paperclip#2076]
Hello,

I hope everyone is having a great holiday.

I'm using rails 4.2.1 and ruby 2.2.1, I have paperclip 4.3.2 installed. I'm wondering if anyone can help with a solution to the following issue. 
I ran into the following error after trying to generate a controller for an index and show page:
<pre>
<code> 
$ rails g controller Project index show
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `has_attached_file' for Project (call 'Project.connection' to establish a connection):Class (NoMethodError)
        from /home/ubuntu/workspace/code_theater/app/models/project.rb:8:in `<class:Project>'
        from /home/ubuntu/workspace/code_theater/app/models/project.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-
[truncated]
</code>
</pre>
Full gist here: https://gist.github.com/NishL/b7ae7254117ea976a1e9
I had just installed the gem, so I though restarting the server would be a good idea, and it worked:
<pre><code>
$ rails g controller Project index show
Running via Spring preloader in process 25084
      create  app/controllers/project_controller.rb
       route  get 'project/show'
       route  get 'project/index'
      invoke  erb
      create    app/views/project
      create    app/views/project/index.html.erb
      create    app/views/project/show.html.erb
      invoke  test_unit
      create    test/controllers/project_controller_test.rb
      invoke  helper
      create    app/helpers/project_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/project.coffee
      invoke    scss
      create      app/assets/stylesheets/project.scss
</code></pre>
BUT THEN, I tried generating another controller and ran into the issue again:
<pre><code>
$ rails g controller Task show
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `has_attached_file' for Project (call 'Project.connection' to establish a connection):Class (NoMethodError)
        from /home/ubuntu/workspace/code_theater/app/models/project.rb:8:in `<class:Project>'
        from /home/ubuntu/workspace/code_theater/app/models/project.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
        from /home/ubuntu/workspace/code_theater/app/admin/project.rb:1:in `<top (required)>'
[truncated]</code></pre>

**Comment by MightyBoosh92** [comment]
I changed paperclip version to 4.2.0 and everything seems to work now.
