### ISSUE TITLE
Refresh styles fails with no such yml file

### ISSUE THREAD

**Issue by joallard** [thoughtbot/paperclip#2079]
Issuing `rake paperclip:refresh:missing_styles` in dev for the first time,

```
|| Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/jon/dev-cr/fjl-28jours/public/system/paperclip_attachments.yml
```

**Comment by tirdadc** [comment]
I started getting this when I upgraded from Ruby 2.2.1 to Ruby 2.2.3, even with the .yml file present.

**Comment by joallard** [comment]
That was in 2.1.6

**Comment by DanAndreasson** [comment]
I am experiencing this as well. Configuration:
 
Ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
Rails 4.2.5
Paperclip 4.3.1

Is there any known workaround?

**Comment by sikachu** [comment]
Sorry for the late reply, but do you mind providing us with the backtrace? (Maybe running rake task with `--trace` flag.) I want to see where it got triggered, as I checked and saw that one place that we refer to that file we already do `rescue Errno::ENOENT` in case the file doesn't exist.

**Comment by 121onto** [comment]
Same issue here.  The trace is as follows:

```bash
Running via Spring preloader in process 24447
** Invoke paperclip:refresh:missing_styles (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute paperclip:refresh:missing_styles
Regenerating Testimonial -> avatar -> [:medium, :thumb]
** Execute paperclip:refresh:thumbnails
  Testimonial Load (0.5ms)  SELECT  "testimonials".* FROM "testimonials" WHERE (avatar_file_name IS NOT NULL)  ORDER BY "testimonials"."id" ASC LIMIT 1000
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - {SANITIZED_APP_DIR}/public/system/paperclip_attachments.yml
/var/lib/gems/2.2.0/gems/paperclip-4.3.5/lib/paperclip/missing_attachment_styles.rb:21:in `initialize'
/var/lib/gems/2.2.0/gems/paperclip-4.3.5/lib/paperclip/missing_attachment_styles.rb:21:in `open'
/var/lib/gems/2.2.0/gems/paperclip-4.3.5/lib/paperclip/missing_attachment_styles.rb:21:in `save_current_attachments_styles!'
/var/lib/gems/2.2.0/gems/paperclip-4.3.5/lib/tasks/paperclip.rake:91:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
{SANITIZED_APP_DIR}/bin/rake:9:in `<top (required)>'
/var/lib/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
Tasks: TOP => paperclip:refresh:missing_styles
```

**Comment by 121onto** [comment]
Fixed by running:

```bash
$ mkdir {SANITIZED_APP_DIR}/public/system
```

Then

```bash
$ bin/rake paperclip:refresh:missing_styles --trace

Running via Spring preloader in process 24473
** Invoke paperclip:refresh:missing_styles (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute paperclip:refresh:missing_styles
Regenerating Testimonial -> avatar -> [:medium, :thumb]
** Execute paperclip:refresh:thumbnails
  Testimonial Load (0.5ms)  SELECT  "testimonials".* FROM "testimonials" WHERE (avatar_file_name IS NOT NULL)  ORDER BY "testimonials"."id" ASC LIMIT 1000
```

**Comment by nruth** [comment]
Doesn't work on Heroku in production right now. That's a pretty big bug if you need to change image sizes!

**Comment by nruth** [comment]
It looks like the line in the trace is the culprit, as there's no catch for the missing file. 
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/missing_attachment_styles.rb#L21

What is this file for anyway? Does it matter that on Heroku it will never be present and gets thrown away after the rake task completes?

**Comment by DanielWright** [comment]
In case this helps anyone, I was able to work around this running a shell into my Heroku app, `mkdir -p /app/public/system`, and then running the rake task from the shell.
