### ISSUE TITLE
Rails, Paperclip, S3, undefined method 'size', Empty @queued_for_write

### ISSUE THREAD

**Issue by anka** [thoughtbot/paperclip#2087]
I am using

    ruby 2.2.0
    paperclip (4.3.2)
    aws-sdk (1.66.0)

when trying to upload a file to AWS S3 I get the following error

    NoMethodError - undefined method `size' for nil:NilClass:
      paperclip (4.3.2) lib/paperclip/attachment.rb:466:in `reset_file_if_original_reprocessed'
      paperclip (4.3.2) lib/paperclip/attachment.rb:110:in `assign'
      paperclip (4.3.2) lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
      activerecord (4.2.0) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
      activerecord (4.2.0) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
      actionpack (4.2.0) lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
      activerecord (4.2.0) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
      activerecord (4.2.0) lib/active_record/persistence.rb:249:in `block in update'
      activerecord (4.2.0) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
      activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
      activerecord (4.2.0) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
      activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
      activerecord (4.2.0) lib/active_record/transactions.rb:220:in `transaction'
      activerecord (4.2.0) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
      activerecord (4.2.0) lib/active_record/persistence.rb:248:in `update'

This error only happens when updating a given object with `update_attributes`, creating a new object and using `save` works fine.
This error seems very odd to me, because the upload to S3 works and the file gets stored there:

    [paperclip] saving /users/2/identity_documents/xxx.PDF
    [AWS S3 200 0.768066 0 retries] put_object(:acl=>:private,:bucket_name=>"imp-staging",:content_length=>167130,:content_type=>"application/pdf",:data=>Paperclip::UploadedFileAdapter: xxx.PDF,:key=>"users/2/identity_documents/xxx.PDF")  

I also noticed, that `@queued_for_write` within the class `Attachment` in the method `reset_file_if_original_reprocessed` is empty.

Anybody observed the same behaviour?

**Comment by anka** [comment]
Closing this issue in cause of #671 and http://stackoverflow.com/questions/34717024/rails-paperclip-s3-undefined-method-size/34743235#34743235
