### ISSUE TITLE
Stack level too deep while saving a model with paperclip 2.7.5

### ISSUE THREAD

**Issue by veelenga** [thoughtbot/paperclip#2115]
I have to use outdated environment (ruby 1.8.7, rails 2.3.5) and trying to integrate paperclip. I faced with a following problem:

```ruby
# model
class GenericFilesystemAttachment < ActiveRecord::Base
  has_attached_file :attachment
end

# test
GenericFilesystemAttachment.create # stack level too deep
```

```
SystemStackError in 'GenericFilesystemAttachment works'
stack level too deep
/Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/activerecord-2.3.5/lib/active_record/base.rb:1475:in `respond_to?'
/Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/paperclip-2.7.5/lib/paperclip.rb:449:in `attachment_definitions'
/Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/paperclip-2.7.5/lib/paperclip.rb:450:in `attachment_definitions'
/Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/paperclip-2.7.5/lib/paperclip.rb:460:in `attachment_for'
/Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/paperclip-2.7.5/lib/paperclip.rb:344:in `attachment'
...
```
Any help is appreciated!

**Comment by maclover7** [comment]
I believe that both Paperclip 2.x and Ruby 1.8.7 are currently unsupported.

**Comment by veelenga** [comment]
Actually it works pretty well, but i can't test it. I found that the issue happens after requiring factory_girl:

```sh
Loading test environment (Rails 2.3.5)
"/Users/vel/.rvm/rubies/ruby-1.8.7-p374/bin/irb"
>> GenericFilesystemAttachment.create
=> #<GenericFilesystemAttachment id: 2, created_at: "2016-02-17 17:30:19", updated_at: "2016-02-17 17:30:19", attachment_content_type: nil, attachment_file_size: nil, attachment_updated_at: nil, attachment_file_name: nil>
>> require "factory_girl"
=> true
>> GenericFilesystemAttachment.create
SystemStackError: stack level too deep
        from /Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/activerecord-2.3.5/lib/active_record/dynamic_finder_match.rb:4:in `match'
        from /Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/activerecord-2.3.5/lib/active_record/base.rb:1475:in `respond_to?'
        from /Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/paperclip-2.8.0/lib/paperclip.rb:449:in `attachment_definitions'
        from /Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/paperclip-2.8.0/lib/paperclip.rb:450:in `attachment_definitions'
        from /Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/paperclip-2.8.0/lib/paperclip.rb:460:in `attachment_for'
        from /Users/vel/.rvm/gems/ruby-1.8.7-p374@hgv4/gems/paperclip-2.8.0/lib/paperclip.rb:344:in `attachment'

```

Any ideas how to avoid it ?

**Comment by veelenga** [comment]
The real issue happens when requiring `active_support/core_ext/class/attribute` (definitely factory girl uses it), which defines `Class.class_attribute`.

The easiest way to solve it is to undefine `:class_attribute` method:

```ruby
class Class
  undef_method :class_attribute
end
```

Have no idea why, when [paperclip base responds to class_attribute](https://github.com/thoughtbot/paperclip/blob/801048d345bde54b44c4e6393b3e3e8c6047a46e/lib/paperclip.rb#L226), stack error happens.
