### ISSUE TITLE
spoof detector using missing method 'type_for' from MIME::Types

### ISSUE THREAD

**Issue by MatthewRalston** [thoughtbot/paperclip#2192]
When loading the MIME::Types class into an irb session, the method `type_for` is accessible. When inspecting the method in a `rails console` session, I see the following error until I load `mime-types` directly.

```
>rails console
Running via Spring preloader in process 19851
Loading development environment (Rails 4.2.6)
2.1.5 :001 > MIME::Types
MIME::Types
2.1.5 :001 > MIME::Types
 => MIME::Types 
2.1.5 :002 > MIME::Types.type_for
NoMethodError: undefined method `type_for' for MIME::Types:Class
    from (irb):2
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
    from /home/ralstonm/Projects/test/bin/rails:9:in `<top (required)>'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /home/ralstonm/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/ralstonm/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'2.1.5 :003 > 
2.1.5 :004 >   require 'mime-types'
 => true 
2.1.5 :005 > MIME::Types.type_for
ArgumentError: wrong number of arguments (0 for 1)
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/mime-types-3.0/lib/mime/types/registry.rb:31:in `type_for'
    from (irb):5
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
    from /home/ralstonm/Projects/test/bin/rails:9:in `<top (required)>'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
    from /home/ralstonm/.rvm/gems/ruby-2.1.5@test/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /home/ralstonm/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/ralstonm/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'2.1.5 :006 > 
```

Also, when submitting a form, I see the following fatal error in my rails application with both 5.0.0.beta2 and 4.3.6:
Log output

```
INFO | 05-05-16 13:54:19 |no trace:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"uOEZjN6/9a3Lux4lvPgXLX7SEq/7tDV9b57hAFGnOYUas7xWcleAIxpqgoF2AHyJLPBnvMlS0GNtywqPwQKPGg==", "request"=>{"fasta"=>#<ActionDispatch::Http::UploadedFile:0x00000008ccac10 @tempfile=#<Tempfile:/tmp/RackMultipart20160505-130002-kqaqkk.txt>, @original_filename="test.txt", @content_type="text/plain", @headers="Content-Disposition: form-data; name=\"request[fasta]\"; filename=\"test.txt\"\r\nContent-Type: text/plain\r\n">}, "commit"=>"Submit"}
DEBUG | 05-05-16 13:54:19 |no trace:   User Load (2.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
INFO | 05-05-16 13:54:20 |no trace: Completed 500 Internal Server Error in 60ms (ActiveRecord: 2.9ms)
FATAL | 05-05-16 13:54:20 |no trace: 
NoMethodError (undefined method `type_for' for MIME::Types:Class):
  app/controllers/request_controller.rb:14:in `create'
```

Offending controller:

```
def create
    @request = Request.new(fasta: params[:request][:fasta])
    @request.save
```

Stack trace

``` ruby
paperclip (5.0.0.beta2) lib/paperclip/media_type_spoof_detector.rb:58:in `content_types_from_name'
paperclip (5.0.0.beta2) lib/paperclip/media_type_spoof_detector.rb:62:in `media_types_from_name'
paperclip (5.0.0.beta2) lib/paperclip/media_type_spoof_detector.rb:37:in `supplied_type_mismatch?'
paperclip (5.0.0.beta2) lib/paperclip/media_type_spoof_detector.rb:33:in `media_type_mismatch?'
paperclip (5.0.0.beta2) lib/paperclip/media_type_spoof_detector.rb:14:in `spoofed?'
paperclip (5.0.0.beta2) lib/paperclip/validators/media_type_spoof_detection_validator.rb:8:in `validate_each'
activemodel (4.2.6) lib/active_model/validator.rb:151:in `block in validate'
activemodel (4.2.6) lib/active_model/validator.rb:148:in `each'
activemodel (4.2.6) lib/active_model/validator.rb:148:in `validate'
paperclip (5.0.0.beta2) lib/paperclip/validators.rb:68:in `block in create_validating_before_filter'
activesupport (4.2.6) lib/active_support/callbacks.rb:446:in `instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:446:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:145:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `each'
activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_fasta_post_process_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
paperclip (5.0.0.beta2) lib/paperclip/callbacks.rb:38:in `run_paperclip_callbacks'
paperclip (5.0.0.beta2) lib/paperclip/attachment.rb:503:in `block in post_process'
activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_post_process_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
paperclip (5.0.0.beta2) lib/paperclip/callbacks.rb:38:in `run_paperclip_callbacks'
paperclip (5.0.0.beta2) lib/paperclip/attachment.rb:502:in `post_process'
paperclip (5.0.0.beta2) lib/paperclip/attachment.rb:458:in `post_process_file'
paperclip (5.0.0.beta2) lib/paperclip/attachment.rb:110:in `assign'
paperclip (5.0.0.beta2) lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
activerecord (4.2.6) lib/active_record/attribute_assignment.rb:54:in `public_send'
activerecord (4.2.6) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
activerecord (4.2.6) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
actionpack (4.2.6) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
actionpack (4.2.6) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
activerecord (4.2.6) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
activerecord (4.2.6) lib/active_record/core.rb:566:in `init_attributes'
activerecord (4.2.6) lib/active_record/core.rb:281:in `initialize'
activerecord (4.2.6) lib/active_record/inheritance.rb:61:in `new'
activerecord (4.2.6) lib/active_record/inheritance.rb:61:in `new'
app/controllers/request_controller.rb:14:in `create'
actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.6) lib/rails/rack/logger.rb:22:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.6) lib/rails/engine.rb:518:in `call'
railties (4.2.6) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (1.6.4) lib/rack/lint.rb:49:in `_call'
rack (1.6.4) lib/rack/lint.rb:37:in `call'
rack (1.6.4) lib/rack/showexceptions.rb:24:in `call'
rack (1.6.4) lib/rack/commonlogger.rb:33:in `call'
rack (1.6.4) lib/rack/chunked.rb:54:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
unicorn (5.1.0) lib/unicorn/http_server.rb:562:in `process_client'
unicorn (5.1.0) lib/unicorn/http_server.rb:658:in `worker_loop'
unicorn (5.1.0) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
unicorn (5.1.0) lib/unicorn/http_server.rb:132:in `start'
unicorn (5.1.0) bin/unicorn:126:in `<top (required)>'
/home/ralstonm/.rvm/gems/ruby-2.1.5@test/bin/unicorn:23:in `load'
/home/ralstonm/.rvm/gems/ruby-2.1.5@test/bin/unicorn:23:in `<main>'
/home/ralstonm/.rvm/gems/ruby-2.1.5@test/bin/ruby_executable_hooks:15:in `eval'
/home/ralstonm/.rvm/gems/ruby-2.1.5@test/bin/ruby_executable_hooks:15:in `<main>'
```

Gem list 

```
*** LOCAL GEMS ***

actionmailer (4.2.6)
actionpack (4.2.6)
actionview (4.2.6)
activejob (4.2.6)
activemodel (4.2.6)
activerecord (4.2.6)
activesupport (4.2.6)
arel (6.0.3)
bcrypt (3.1.11)
...
mime-types (3.0)
mime-types-data (3.2016.0221)
mimemagic (0.3.1, 0.3.0)
...
nokogiri (1.6.7.2)
paperclip (5.0.0.beta2) OR (4.3.6)
pg (0.18.4)
pry (0.10.3)
psych (2.0.5)
puma (3.4.0)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.6)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
railties (4.2.6)
raindrops (0.16.0)
rake (11.1.2, 10.1.0)
rdoc (4.2.2, 4.1.0)
rubygems-bundler (1.4.4)


```

**Comment by MatthewRalston** [comment]
After discovering the anomaly in the rails-console, I directly loaded 'mime-types' into my controller (and namespace) and the problem disappeared.

**Comment by tute** [comment]
Glad you found the issue. Is this a bug in paperclip, or was it in your setup?

**Comment by MatthewRalston** [comment]
@tute it seems like it is paperclip. It's reasonable to expect that the correct class `MIME::Types` should be in the namespace when paperclip calls that method, no?

**Comment by tute** [comment]
It's marked as a dependency, so it should be loaded:

`./paperclip.gemspec:  s.add_dependency('mime-types')`

Do you have a `require: false` option in your Gemfile?

**Comment by MatthewRalston** [comment]
It is not in a particular group in my Gemfile and is a universal dependency. Could it be masked by loading the other MIME::Types module somewhere in the application? As you can see I'm using ruby 2.1.5 and rails 4.2.6... I'm not familiar with this other MIME::Types module.
Gemfile
```
# Use Paperclip for fileuploads
#gem 'paperclip' # 4.3.6
gem 'paperclip', '~> 5.0.0.beta2'
```

**Comment by tute** [comment]
I'm not sure why your app would behave this way. I never heard this issue before.

Could you move forward with it, without needing to explicitly include that gem? Should we keep this issue open, even though it doesn't look like a bug in paperclip?

**Comment by MatthewRalston** [comment]
Again, I think that if it's not an explicit bug in paperclip, we should update the documentation/example (from README.md, below) and close the issue. It seemed that adding the gem to the project was not enough, since somehow the other MIME::Type class has no method "type_for".

Example from README.md:
`controllers/book_controller.rb` should have `require mime-types` at the top

```ruby
require mime-types
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.document = params[:book][:document]
    @book.save
    respond_with @book
  end
```

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
