### ISSUE TITLE
validates attachment size: ArgumentError - comparison of String with 0 failed

### ISSUE THREAD

**Issue by jufemaiz** [thoughtbot/paperclip#2442]
I can confirm that I'm still seeing https://github.com/thoughtbot/paperclip/issues/1692 right now. Resurrecting as it's currently closed but needs to be opened.

db/schema.rb

```Ruby
    t.string   "avatar_file_name",               limit: 255
    t.string   "avatar_content_type",            limit: 255
    t.integer  "avatar_file_size"
    t.datetime "avatar_updated_at"
```

psql:

```Postgresql
 avatar_file_name               | character varying(255)      |
 avatar_content_type            | character varying(255)      |
 avatar_file_size               | integer                     |
 avatar_updated_at              | timestamp without time zone |
```

Error thrown when using validation of file size using:

```Ruby
validates_attachment_size :avatar, less_than: 1.megabytes
```

Stack thrown:

```Ruby
ArgumentError - comparison of String with 0 failed:
  activesupport (4.2.8) lib/active_support/number_helper/number_to_rounded_converter.rb:20:in `convert'
  activesupport (4.2.8) lib/active_support/number_helper/number_converter.rb:132:in `execute'
  activesupport (4.2.8) lib/active_support/number_helper/number_converter.rb:118:in `convert'
  activesupport (4.2.8) lib/active_support/number_helper/number_to_human_size_converter.rb:21:in `convert'
  activesupport (4.2.8) lib/active_support/number_helper/number_converter.rb:132:in `execute'
  activesupport (4.2.8) lib/active_support/number_helper/number_converter.rb:118:in `convert'
  activesupport (4.2.8) lib/active_support/number_helper.rb:238:in `number_to_human_size'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:74:in `human_size'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:88:in `max_value_in_human_size'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:32:in `block (2 levels) in validate_each'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:29:in `block in validate_each'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:23:in `validate_each'
  activemodel (4.2.8) lib/active_model/validator.rb:151:in `block in validate'
  activemodel (4.2.8) lib/active_model/validator.rb:148:in `validate'
  paperclip (5.1.0) lib/paperclip/validators.rb:68:in `block in create_validating_before_filter'
```

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
