### ISSUE TITLE
Getting "no implicit conversion of String into Integer" for S3 storage

### ISSUE THREAD

**Issue by normancapule** [thoughtbot/paperclip#2491]
Hello all! 

Can anyone please help me? I'm upgrading a Rails 4.2 app to 5.1. Unfortunately, I'm getting this error when the model instance calls the attached file:

```
      TypeError:
        no implicit conversion of String into Integer
```

Here is the model:
```
class Product < ApplicationRecord
  ...
  has_attached_file :cover,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
  ...
```

Here is the paperclip config:
```
    config.paperclip_defaults = {
      storage: :s3,
      url: ':s3_domain_url',
      path: '/:class/:attachment/:id_partition/:style/:filename',
      s3_region: 'sa-east-1',
      s3_credentials: {
        bucket: ENV['AWS_S3_BUCKET'],
        access_key_id: ENV['AWS_ACCESS_KEY'],
        secret_access_key: ENV['AWS_SECRET_KEY']
      }
    }
```
Versions:
```
    ruby (2.4.1)
    aws-sdk (2.10.55)
    paperclip (5.1.0)
```
Here is the backtrace:
```
.rvm/gems/ruby-2.4.1@purifier/gems/paperclip-5.1.0/lib/paperclip/storage/s3.rb:125:in `extended'
.rvm/gems/ruby-2.4.1@purifier/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:428:in `extend'
.rvm/gems/ruby-2.4.1@purifier/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:428:in `initialize_storage'
.rvm/gems/ruby-2.4.1@purifier/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:90:in `initialize'
.rvm/gems/ruby-2.4.1@purifier/gems/paperclip-5.1.0/lib/paperclip/has_attached_file.rb:47:in `new'
.rvm/gems/ruby-2.4.1@purifier/gems/paperclip-5.1.0/lib/paperclip/has_attached_file.rb:47:in `block in define_instance_getter'
.rvm/gems/ruby-2.4.1@purifier/gems/activemodel-5.1.4/lib/active_model/validator.rb:148:in `block in validate'
.rvm/gems/ruby-2.4.1@purifier/gems/activemodel-5.1.4/lib/active_model/validator.rb:147:in `each'
.rvm/gems/ruby-2.4.1@purifier/gems/activemodel-5.1.4/lib/active_model/validator.rb:147:in `validate'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:413:in `block in make_lambda'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:600:in `catch'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:600:in `block in default_terminator'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:198:in `block in halting'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `block in invoke_before'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `each'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `invoke_before'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:130:in `run_callbacks'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_validate_callbacks'
.rvm/gems/ruby-2.4.1@purifier/gems/activemodel-5.1.4/lib/active_model/validations.rb:405:in `run_validations!'
.rvm/gems/ruby-2.4.1@purifier/gems/activemodel-5.1.4/lib/active_model/validations/callbacks.rb:110:in `block in run_validations!'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_validation_callbacks'
.rvm/gems/ruby-2.4.1@purifier/gems/activemodel-5.1.4/lib/active_model/validations/callbacks.rb:110:in `run_validations!'
.rvm/gems/ruby-2.4.1@purifier/gems/activemodel-5.1.4/lib/active_model/validations.rb:335:in `valid?'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/validations.rb:65:in `valid?'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/validations.rb:82:in `perform_validations'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/validations.rb:50:in `save!'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/transactions.rb:313:in `block in save!'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/transactions.rb:313:in `save!'
.rvm/gems/ruby-2.4.1@purifier/gems/activerecord-5.1.4/lib/active_record/suppressor.rb:46:in `save!'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/configuration.rb:18:in `block in initialize'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/evaluation.rb:15:in `create'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/strategy/create.rb:12:in `block in result'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/strategy/create.rb:9:in `tap'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/strategy/create.rb:9:in `result'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/factory.rb:42:in `run'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/factory_runner.rb:29:in `block in run'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/factory_runner.rb:28:in `run'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/strategy/create.rb:5:in `association'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/evaluator.rb:33:in `association'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/attribute/association.rb:19:in `block in to_proc'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/evaluator.rb:77:in `instance_exec'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/evaluator.rb:77:in `block in define_attribute'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/attribute_assigner.rb:56:in `get'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/attribute_assigner.rb:15:in `each'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/attribute_assigner.rb:14:in `tap'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/attribute_assigner.rb:14:in `object'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/evaluation.rb:12:in `object'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/strategy/create.rb:9:in `result'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/factory.rb:42:in `run'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/factory_runner.rb:29:in `block in run'
.rvm/gems/ruby-2.4.1@purifier/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/factory_runner.rb:28:in `run'
.rvm/gems/ruby-2.4.1@purifier/gems/factory_girl-4.8.1/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
# ./spec/services/reservation_processor_spec.rb:8:in `block (2 levels) in <top (required)>'
```

Thanks so much for the time!

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
