### ISSUE TITLE
S3 Accelerate Endpoint error on aws-sdk <= 2.2.*

### ISSUE THREAD

**Issue by fixr** [thoughtbot/paperclip#2543]
There seems to be a bug on `>=5.2.0` when fixed to an older but still supported version of `aws-sdk`:

```
ArgumentError (invalid configuration option `:use_accelerate_endpoint'):
  aws-sdk-core (2.2.14) lib/seahorse/client/configuration.rb:160:in `rescue in block in apply_options'
  aws-sdk-core (2.2.14) lib/seahorse/client/configuration.rb:156:in `block in apply_options'
  aws-sdk-core (2.2.14) lib/seahorse/client/configuration.rb:155:in `each'
  aws-sdk-core (2.2.14) lib/seahorse/client/configuration.rb:155:in `apply_options'
  aws-sdk-core (2.2.14) lib/seahorse/client/configuration.rb:143:in `build!'
  aws-sdk-core (2.2.14) lib/seahorse/client/base.rb:68:in `build_config'
  aws-sdk-core (2.2.14) lib/seahorse/client/base.rb:19:in `initialize'
  aws-sdk-core (2.2.14) lib/seahorse/client/base.rb:105:in `new'
  aws-sdk-resources (2.2.14) lib/aws-sdk-resources/resource.rb:169:in `extract_client'
  aws-sdk-resources (2.2.14) lib/aws-sdk-resources/resource.rb:15:in `initialize'
  paperclip (5.2.1) lib/paperclip/storage/s3.rb:269:in `new'
  paperclip (5.2.1) lib/paperclip/storage/s3.rb:269:in `obtain_s3_instance_for'
  paperclip (5.2.1) lib/paperclip/storage/s3.rb:263:in `s3_interface'
  paperclip (5.2.1) lib/paperclip/storage/s3.rb:273:in `s3_bucket'
  paperclip (5.2.1) lib/paperclip/storage/s3.rb:281:in `s3_object'
  paperclip (5.2.1) lib/paperclip/storage/s3.rb:326:in `exists?'
  paperclip (5.2.1) lib/paperclip/attachment.rb:569:in `block in queue_all_for_delete'
  paperclip (5.2.1) lib/paperclip/attachment.rb:568:in `map'
  paperclip (5.2.1) lib/paperclip/attachment.rb:568:in `queue_all_for_delete'
  paperclip (5.2.1) lib/paperclip/attachment.rb:259:in `clear'
  paperclip (5.2.1) lib/paperclip/attachment.rb:107:in `assign'
  paperclip (5.2.1) lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
...
```

I think the problem lies on this line:

https://github.com/thoughtbot/paperclip/blob/v5.2.1/lib/paperclip/storage/s3.rb#L257

It sets the option to `false`, despite the `aws-sdk` version. It should probably be considered as in here: https://github.com/thoughtbot/paperclip/blob/v5.2.1/lib/paperclip/storage/s3.rb#L161-L163.

I know that's an older version of `aws-sdk`, but I suppose there might be others like us that have it fixed for any particular reason.

Thanks!

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
