### ISSUE TITLE
Trouble creating the migration converting to Active Storage

### ISSUE THREAD

**Issue by hazmatzo** [thoughtbot/paperclip#2603]
I have this code, which I copied from the ActiveStorage migration guide:

```
    active_storage_blob_statement = ActiveRecord::Base.connection.raw_connection.prepare(<<-SQL)
      INSERT INTO active_storage_blobs (
        `key`, filename, content_type, metadata, byte_size, checksum, created_at
      ) VALUES (?, ?, ?, '{}', ?, ?, ?)
    SQL
```

And it's giving me this error when I attempt to migrate:

```
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 1, expected 2..3)
project/db/migrate/20180523202013_convert_to_active_storage.rb:16:in `prepare'
project/db/migrate/20180523202013_convert_to_active_storage.rb:16:in `up'
project/bin/rails:9:in `<top (required)>'
project/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ArgumentError: wrong number of arguments (given 1, expected 2..3)
project/db/migrate/20180523202013_convert_to_active_storage.rb:16:in `prepare'
project/db/migrate/20180523202013_convert_to_active_storage.rb:16:in `up'
project/bin/rails:9:in `<top (required)>'
project/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
```

**Comment by twest7** [comment]
Same error, can't seem to fix it yet

**Comment by rnbronstein** [comment]
I am having this same error and I'm having trouble debugging.

**Comment by colinpetruno** [comment]
I ran into this as well since the example doesn't work for postgres. Here's a completed gist of a rake task with a few changes to ensure it would run with some spotty seed data. 

https://gist.github.com/colinpetruno/037de4fafa4cff695b1d7905cd6fd7c2

**Comment by mike-burns** [comment]
I've opened a PR for this: https://github.com/thoughtbot/paperclip/pull/2613 .
