### ISSUE TITLE
With Ruby 3.0 validator produces "ArgumentError: wrong number of arguments (given 3, expected 1..2)"

### ISSUE THREAD

**Issue by vtamara** [thoughtbot/paperclip#2673]
The regression tests of an open source rails work good with Ruby 2.7 as can be seen at:
<https://travis-ci.org/github/pasosdeJesus/sip/jobs/760216854#L960>

However with Ruby 3.0 the following errors appear (as can be seen at <https://travis-ci.org/github/pasosdeJesus/sip/jobs/760216854#L976>):
```
1) Error:

Sip::AnexoTest#test_no_valido_1:

ArgumentError: wrong number of arguments (given 3, expected 1..2)

    /home/travis/build/pasosdeJesus/sip/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.3/lib/active_model/errors.rb:404:in `add'

    /home/travis/build/pasosdeJesus/sip/vendor/bundle/ruby/3.0.0/gems/paperclip-6.1.0/lib/paperclip/validators/attachment_presence_validator.rb:8:in `validate_each'
...
```

and

```
2) Error:

Sip::AnexoTest#test_no_valido_2:

ArgumentError: wrong number of arguments (given 3, expected 1..2)

    /home/travis/build/pasosdeJesus/sip/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.3/lib/active_model/errors.rb:404:in `add'

    /home/travis/build/pasosdeJesus/sip/vendor/bundle/ruby/3.0.0/gems/paperclip-6.1.0/lib/paperclip/validators/attachment_presence_validator.rb:8:in `validate_each'
...
```

Both are related to expressions `anexo.valid?` where `anexo` is amodel with a paperclip attachment.

**Comment by gdonald** [comment]
I'm hitting this same issue with Ruby 3.1.0.  Any ETA on the fix?

**Comment by vtamara** [comment]
I switch to kt-paperclip

**Comment by maxvlc** [comment]
The thing is that I also need `'paperclip-optimizer'` which seems that install original `paperclip`
I installed [kt-paperclip-optimizer](https://github.com/loco2/kt-paperclip-optimizer), but it also install in the background original `paperclip` gem, which causes that error:

```
ArgumentError:
       wrong number of arguments (given 3, expected 1..2
```

That's a part of my `Gemfile.lock` where is installed `paperclip`

```
    paperclip (6.1.0)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      mime-types
      mimemagic (~> 0.3.0)
      terrapin (~> 0.6.0)
    paperclip-optimizer (2.0.0)
      image_optim (~> 0.19)
      paperclip (>= 3.4)
```

Someone knows how to avoid that dependency and just keep installed `kt-paperclip`¿?

**Comment by joshuapinter** [comment]
@maxvlc Can you not just fork the project and update the dependency in the `.gemspec` file?

**Comment by maxvlc** [comment]
> @maxvlc Can you not just fork the project and update the dependency in the `.gemspec` file?

Yep, that's the point, fork the gem and keep it on our project.
