### ISSUE TITLE
Webp image upload issue

### ISSUE THREAD

**Issue by SRIKANTHAR** [thoughtbot/paperclip#2706]
## Deprecation notice

Paperclip is currently undergoing [deprecation in favor of ActiveStorage](https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md). Maintainers of this repository will no longer be tending to new issues. We're leaving the issues page open so Paperclip users can still see & search through old issues, and continue existing discussions if they wish.

**Comment by SRIKANTHAR** [comment]
webp images upload not supported it's giving this error message when trying to upload webp images has below

ImageSpec::Error (#<Paperclip::Tempfile:/tmp/18c5a2261d1d178068acb724a8a967b720221108-1242657-rpwwg520221108-1242657-n7zd3k.webp> is not a supported image format. Sorry bub :():
  app/helpers/media_helper.rb:567:in `create_media'
  app/controllers/media_controller.rb:391:in `create'

please help on this to how to fix this issue

**Comment by sasharevzin** [comment]
@SRIKANTHAR you better try to ask the question at https://github.com/kreeti/kt-paperclip
