### ISSUE TITLE
Error when try creating a new attachment

### ISSUE THREAD

**Issue by yega** [thoughtbot/paperclip#671]
When i try creating new attachment, i get:

A NoMethodError occurred in assets#create:

```
  undefined method `size' for nil:NilClass
  paperclip (2.4.5) lib/paperclip/attachment.rb:121:in `assign'
```

Аfter migrating from 2.3.16 and got this error, even though the file is saved. But this mistake breke further logic.

``` ruby
  has_attached_file :asset, :styles => {:preview => {:geometry => "112x84#",
                                                     :quality => 10,
                                                     :format => "jpg",
                                                     :name => "preview"},
                                        :main => {
                                                  :geometry => "496x370#",
                                                  :quality => 50,
                                                  :format => "jpg",
                                                  :name => "main"
                                        },
                                        :half => {
                                          :geometry => "240x180#",
                                          :quality => 50,
                                          :format => 'jpg',
                                          :name => 'half'
                                        },
                                        :album => {
                                          :geometry => "800x",
                                          :quality => 50,
                                          :format => 'jpg',
                                          :name => 'album'
                                        }
                                      }
```

**Comment by rbq** [comment]
I just wanted to report that I have an issue that I believe to be related. I use Paperclip 5.1.0 and the Ancestry 2.1.0 Gem. When I do an `insert_at` after assigning the attachments …

```ruby
thingie.picture = picture if picture
thingie.insert_at position
thingie.save!
```

… I get a mysterious exception:

```
TypeError: no implicit conversion of nil into String
[...]/storage/filesystem.rb:38:in `dirname'
[...]/storage/filesystem.rb:38:in `block in flush_writes'
[...]/storage/filesystem.rb:37:in `each'
[...]/storage/filesystem.rb:37:in `flush_writes'
[...]/attachment.rb:244:in `save'
```

This on the other hand works perfectly fine:

```ruby
thingie.insert_at position
thingie.picture = picture if picture
thingie.save!
```

**Comment by tute** [comment]
It looks like you are using `insert_at` for the generated file path?
