### ISSUE TITLE
paperclip_fixture does not work in Factories

### ISSUE THREAD

**Issue by 505aaron** [thoughtbot/paperclip#778]
# Setup
I am using Rspec with following gems.
* Rails 3.0.1
* Paperclip 2.7.0
* factory_girl (2.6.3)
* factory_girl_rails (1.7.0)
* rspec (2.8.0)

# Issue
I am trying to follow the example in the documentation:
    #   Factory.define :band_with_demo_tape, :parent => :band do |band|
    #     band.demo_tape { band.paperclip_fixture("band", "demo_tape", "png") }
    #   end
    def paperclip_fixture(model, attachment, extension)

I am trying to use this to add some UT's, but I have not been successful. How do I use it correctly?

#### Spec Helper
Here is a simplified version:

    ENV["RAILS_ENV"] ||= 'test'
    require File.expand_path("../../config/environment", __FILE__)
    require 'rspec/rails'
    require 'rspec/autorun'
    require 'faker'
    require 'paperclip/matchers'
    require 'fakeweb'
    
    Dir[Rails.root.join("spec/support/**/*.rb")].each { |f| require f }
    
    RSpec.configure do |config|
      config.fixture_path = "#{::Rails.root}/spec/fixtures"
      config.use_transactional_fixtures = true
      config.infer_base_class_for_anonymous_controllers = false
      config.include Paperclip::Shoulda::Matchers
    end

#### Factories
    Factory.define :user, :class => User do |t|
      t.ignore do
        upcase { false }
        downcase { false }
      end
    
      t.username { UserHelper::valid_username(User::USERNAME_RANGE) }
      t.email { Faker::Internet.email }
      t.password "password1"
      t.name { UserHelper::valid_name }
    
      t.after_build do |user, evaluator|
        user.confirmed_at = DateTime.now
      end
    
      t.after_create do |user, evaluator|
        user.name.upcase! if evaluator.upcase
        user.name.downcase! if evaluator.downcase
      end
    end
    
    Factory.define :user_with_photo, :parent => :user do |factory|
      factory.photo { factory.paperclip_fixture("user", "photo", "jpeg") }#Rack::Test::UploadedFile("") }
    end
#### Test
When I try to build the model in an rspec test, for example:
    @user = Factory.build(:user_with_photo)#, :user => @user)
I get the following stack:
```
ArgumentError: Trait not registered: empty?
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/registry.rb:16:in `find'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl.rb:68:in `trait_by_name'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/definition.rb:69:in `trait_by_name'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/definition.rb:65:in `additional_traits'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/definition.rb:65:in `map'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/definition.rb:65:in `additional_traits'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/definition.rb:26:in `processing_order'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/factory.rb:19:in `__send__'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/factory.rb:19:in `processing_order'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/factory.rb:116:in `attributes'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/factory.rb:115:in `tap'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/factory.rb:115:in `attributes'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/factory.rb:110:in `evaluator_class'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/factory.rb:45:in `run'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/factory_runner.rb:25:in `run'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/syntax/methods.rb:40:in `build'
Library/Ruby/Gems/1.8/gems/factory_girl-2.6.3/lib/factory_girl/syntax/vintage.rb:119:in `build'
Users/acordova05/Kuato2/spec/models/user_model_spec.rb:19:
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `instance_eval'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `run_in'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `run_all'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `each'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `run_all'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:368:in `run_hook'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `run_before_each_hooks'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `each'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `run_before_each_hooks'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:217:in `run_before_each'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:79:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `run_examples'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
Library/Ruby/Gems/1.8/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `autorun'
```

**Comment by maclover7** [comment]
Hi @505aaron and @ResidentBio ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
If we can't replicate the error (and there's no activity around this issue), I hope things are working well now for you. I’ll close the issue, happy to continue further discussion if we can find the problem and potential fix for it. Thanks for your input!
