### ISSUE TITLE
TypeError (no _dump_data is defined for class Proc)

### ISSUE THREAD

**Issue by garyharan** [thoughtbot/paperclip#819]
I keep getting this error after adding attachments to my Company model.

```
Started POST "/companies/36/applications" for 127.0.0.1 at 2012-04-08 14:39:27 -0400
Processing by ApplicationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"p6YauDkASCx2CAUb7pD3Egse9ZhMkwr1sobZiFCsyik=", "application"=>{"office_id"=>"41", "department_id"=>"344", "type_id"=>"1", "level_id"=>"1", "compensation_id"=>"1", "resume"=>#<ActionDispatch::Http::UploadedFile:0x007f8e1af9f290 @original_filename="application.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"application[resume]\"; filename=\"application.pdf\"\r\nContent-Type: application/pdf\r\n", @tempfile=#<File:/var/folders/7g/jnvbjjy56n5bfjb_j92l7yq80000gn/T/RackMultipart20120408-68813-faopbu>>}, "commit"=>"Save", "company_id"=>"36"}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 60]]
  Company Load (0.1ms)  SELECT "companies".* FROM "companies" WHERE "companies"."id" = ? LIMIT 1  [["id", "36"]]
   (0.1ms)  begin transaction
Binary data inserted for `string` type on column `resume_content_type`
  SQL (1.2ms)  INSERT INTO "applications" ("company_id", "compensation_id", "created_at", "department_id", "level_id", "office_id", "resume_content_type", "resume_file_name", "resume_file_size", "type_id", "updated_at", "user_id") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["company_id", 36], ["compensation_id", 1], ["created_at", Sun, 08 Apr 2012 18:39:27 UTC +00:00], ["department_id", 344], ["level_id", 1], ["office_id", 41], ["resume_content_type", "application/pdf"], ["resume_file_name", "application.pdf"], ["resume_file_size", 215097], ["type_id", 1], ["updated_at", Sun, 08 Apr 2012 18:39:27 UTC +00:00], ["user_id", 60]]
[paperclip] Saving attachments.
[paperclip] saving /application_resumes/45/application.pdf
[AWS S3 200 4.083532 0 retries] put_object(:acl=>:public_read,:bucket_name=>"qwalify_developnent",:content_type=>"application/pdf",:data=>#<Paperclip::UploadedFileAdapter:0x007f8e1acb7b40 @target=#<ActionDispatch::Http::UploadedFile:0x007f8e1af9f290 @original_filename="application.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"application[resume]\"; filename=\"application.pdf\"\r\nContent-Type: application/pdf\r\n", @tempfile=#<File:/var/folders/7g/jnvbjjy56n5bfjb_j92l7yq80000gn/T/RackMultipart20120408-68813-faopbu>>, @tempfile=#<File:/var/folders/7g/jnvbjjy56n5bfjb_j92l7yq80000gn/T/application.pdf20120408-68813-11au1jk>>,:key=>"application_resumes/45/application.pdf")  

   (1.2ms)  commit transaction
Redirected to http://localhost:3000/companies/36/applications/45/edit
Completed 302 Found in 4097ms (ActiveRecord: 2.7ms)

TypeError (no _dump_data is defined for class Proc):
  activesupport (3.2.2) lib/active_support/message_verifier.rb:53:in `dump'
  activesupport (3.2.2) lib/active_support/message_verifier.rb:53:in `generate'
  actionpack (3.2.2) lib/action_dispatch/middleware/cookies.rb:297:in `[]='
  actionpack (3.2.2) lib/action_dispatch/middleware/session/cookie_store.rb:67:in `set_cookie'
  rack (1.4.1) lib/rack/session/abstract/id.rb:330:in `commit_session'
  rack (1.4.1) lib/rack/session/abstract/id.rb:206:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.2) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:443:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `_run__2351691287891496561__call__463823622450231230__callbacks'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.2) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.2) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/static.rb:61:in `call'
  railties (3.2.2) lib/rails/engine.rb:479:in `call'
  railties (3.2.2) lib/rails/application.rb:220:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in `call'
  railties (3.2.2) lib/rails/rack/log_tailer.rb:14:in `call'
  rack (1.4.1) lib/rack/handler/webrick.rb:59:in `service'
  /Users/john/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /Users/john/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /Users/john/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'


  Rendered /Users/john/.rvm/gems/ruby-1.9.3-p125@qwalify.com/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.6ms)
  Rendered /Users/john/.rvm/gems/ruby-1.9.3-p125@qwalify.com/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.7ms)
  Rendered /Users/john/.rvm/gems/ruby-1.9.3-p125@qwalify.com/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (10.7ms)
```

Anyone have any clue what's happening here?

**Comment by tak1n** [comment]
@ehudros: thx for you're solution, you kinda saved me from debugging this the whole night :D

**Comment by tak1n** [comment]
For any other which stumble upon this problem, this basically breaks fragment caching for rails.
Not sure if this should be reopened?

**Comment by masterkain** [comment]
I have two procs currently: `s3_host_alias` and `s3_credentials`, and I cannot `Marshal.dump` an instance of the object with the attachment macro (`TypeError: no _dump_data is defined for class Proc`)

Now to find a workaround...

**Comment by masterkain** [comment]
One solution is to convert proc definitions to strings like this:

`s3_credentials: %{ ->(attachment) { attachment.instance.store_s3_keys } }`

and then monkey patch paperclip depending on your attributes, in my case I had to override `s3_host_alias` and `parse_credentials` in order to `eval` the String first.

**Comment by NeoElit** [comment]
Facing the same issue here. Any updates on how to handle this neatly?
Caching (via Marshal dump on redis) seems to be fine when loading from db, but doing it on AR callback like after_save is causing issues for me.

**Comment by NeoElit** [comment]
@ehudros suggestion also failed to work as Marshal dump is trying to push even the attachment file to cache when uploading the attachment. Seem like a better strategy would be to cache model when loaded from db or a custom serialised object.
